/* This function has been automatically generated by whtgen. */

/*
  apply_small3( <wht>, <S>, <x> )
  ------------------------------
  computes
    WHT_(2^3) with stride <S>
  on the vector <x>
*/

#include "spiral_wht.h"

void apply_small3(Wht *W, long S, wht_value *x)
{
  wht_value t0;
  wht_value t1;
  wht_value t2;
  wht_value t3;
  wht_value t4;
  wht_value t5;
  wht_value t6;
  wht_value t7;
  wht_value t8;
  wht_value t9;
  wht_value t10;
  wht_value t11;
  wht_value t12;
  wht_value t13;
  wht_value t14;
  wht_value t15;




  t0 = x[0] + x[S];
  t1 = x[0] - x[S];
  t2 = x[2 * S] + x[3 * S];
  t3 = x[2 * S] - x[3 * S];
  t4 = t0 + t2;
  t6 = t0 - t2;
  t5 = t1 + t3;
  t7 = t1 - t3;
  t8 = x[4 * S] + x[5 * S];
  t9 = x[4 * S] - x[5 * S];
  t10 = x[6 * S] + x[7 * S];
  t11 = x[6 * S] - x[7 * S];
  t12 = t8 + t10;
  t14 = t8 - t10;
  t13 = t9 + t11;
  t15 = t9 - t11;
  x[0] = t4 + t12;
  x[4 * S] = t4 - t12;
  x[S] = t5 + t13;
  x[5 * S] = t5 - t13;
  x[2 * S] = t6 + t14;
  x[6 * S] = t6 - t14;
  x[3 * S] = t7 + t15;
  x[7 * S] = t7 - t15;
}
