/* This function has been automatically generated by whtgen. */

/*
  apply_small4( <wht>, <S>, <x> )
  ------------------------------
  computes
    WHT_(2^4) with stride <S>
  on the vector <x>
*/

#include "spiral_wht.h"

void apply_small4(Wht *W, long S, wht_value *x)
{
  wht_value t0;
  wht_value t1;
  wht_value t2;
  wht_value t3;
  wht_value t4;
  wht_value t5;
  wht_value t6;
  wht_value t7;
  wht_value t8;
  wht_value t9;
  wht_value t10;
  wht_value t11;
  wht_value t12;
  wht_value t13;
  wht_value t14;
  wht_value t15;
  wht_value t16;
  wht_value t17;
  wht_value t18;
  wht_value t19;
  wht_value t20;
  wht_value t21;
  wht_value t22;
  wht_value t23;
  wht_value t24;
  wht_value t25;
  wht_value t26;
  wht_value t27;
  wht_value t28;
  wht_value t29;
  wht_value t30;
  wht_value t31;
  wht_value t32;
  wht_value t33;
  wht_value t34;
  wht_value t35;
  wht_value t36;
  wht_value t37;
  wht_value t38;
  wht_value t39;
  wht_value t40;
  wht_value t41;
  wht_value t42;
  wht_value t43;
  wht_value t44;
  wht_value t45;
  wht_value t46;
  wht_value t47;




  t0 = x[0] + x[S];
  t1 = x[0] - x[S];
  t2 = x[2 * S] + x[3 * S];
  t3 = x[2 * S] - x[3 * S];
  t4 = t0 + t2;
  t6 = t0 - t2;
  t5 = t1 + t3;
  t7 = t1 - t3;
  t8 = x[4 * S] + x[5 * S];
  t9 = x[4 * S] - x[5 * S];
  t10 = x[6 * S] + x[7 * S];
  t11 = x[6 * S] - x[7 * S];
  t12 = t8 + t10;
  t14 = t8 - t10;
  t13 = t9 + t11;
  t15 = t9 - t11;
  t16 = t4 + t12;
  t20 = t4 - t12;
  t17 = t5 + t13;
  t21 = t5 - t13;
  t18 = t6 + t14;
  t22 = t6 - t14;
  t19 = t7 + t15;
  t23 = t7 - t15;
  t24 = x[8 * S] + x[9 * S];
  t25 = x[8 * S] - x[9 * S];
  t26 = x[10 * S] + x[11 * S];
  t27 = x[10 * S] - x[11 * S];
  t28 = t24 + t26;
  t30 = t24 - t26;
  t29 = t25 + t27;
  t31 = t25 - t27;
  t32 = x[12 * S] + x[13 * S];
  t33 = x[12 * S] - x[13 * S];
  t34 = x[14 * S] + x[15 * S];
  t35 = x[14 * S] - x[15 * S];
  t36 = t32 + t34;
  t38 = t32 - t34;
  t37 = t33 + t35;
  t39 = t33 - t35;
  t40 = t28 + t36;
  t44 = t28 - t36;
  t41 = t29 + t37;
  t45 = t29 - t37;
  t42 = t30 + t38;
  t46 = t30 - t38;
  t43 = t31 + t39;
  t47 = t31 - t39;
  x[0] = t16 + t40;
  x[8 * S] = t16 - t40;
  x[S] = t17 + t41;
  x[9 * S] = t17 - t41;
  x[2 * S] = t18 + t42;
  x[10 * S] = t18 - t42;
  x[3 * S] = t19 + t43;
  x[11 * S] = t19 - t43;
  x[4 * S] = t20 + t44;
  x[12 * S] = t20 - t44;
  x[5 * S] = t21 + t45;
  x[13 * S] = t21 - t45;
  x[6 * S] = t22 + t46;
  x[14 * S] = t22 - t46;
  x[7 * S] = t23 + t47;
  x[15 * S] = t23 - t47;
}
